dist: xenial
language: python
cache: pip
install:
- pip3 install poetry
- poetry install
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.5
  - os: linux
    sudo: required
    python: 3.6
  - os: linux
    sudo: required
    python: 3.7
    env: DEPLOY=yes
  - os: osx
    language: generic
script:
- bash scripts/test.sh
after_script:
- bash <(curl -s https://codecov.io/bash)
